/**
 * GEODE Payment Email Automation
 *
 * Handles automated emails for the GEODE payment workflow:
 * 1. Accounting setup email when contract is sent for signature
 * 2. Invoice reminder emails when payment milestones are triggered
 *
 * Invoice Template Location: /Users/trentmcfadyen/Documents/Project InnerSpace/GEODE/GEODE Invoice Template.docx
 */

// ============================================
// TYPES
// ============================================

export interface AuthorInfo {
  name: string;
  email: string;
  chapter: string;
  chapterTitle: string;
  state: string;
}

export interface ContractInfo {
  authorInfo: AuthorInfo;
  contractUrl?: string;
  contractAttachmentPath?: string;
  paymentAmount?: string;
  paymentSchedule?: string;
}

export interface PaymentTriggerInfo {
  authorInfo: AuthorInfo;
  milestone: string;
  milestoneLabel: string;
  paymentNumber: number;
  paymentAmount?: string;
}

// ============================================
// EMAIL RECIPIENTS
// ============================================

export const GEODE_EMAIL_RECIPIENTS = {
  // Invoice submission addresses
  invoice: 'invoice@projectinnerspace.org',
  accounting: 'accounting@projectinnerspace.org',
  geode: 'geode@projectinnerspace.org',

  // Internal team
  dani: 'dani@projectinnerspace.org', // InnerSpace signatory
};

// ============================================
// EMAIL TEMPLATES
// ============================================

/**
 * Email sent to Accounting when contract is sent for signature
 * CC: Dani (InnerSpace signatory)
 */
export function generateAccountingSetupEmail(contract: ContractInfo): {
  to: string[];
  cc: string[];
  subject: string;
  body: string;
} {
  const { authorInfo, paymentAmount, paymentSchedule } = contract;

  return {
    to: [GEODE_EMAIL_RECIPIENTS.accounting],
    cc: [GEODE_EMAIL_RECIPIENTS.dani],
    subject: `[GEODE] New Contractor Setup - ${authorInfo.name} (${authorInfo.state} Report)`,
    body: `Hi Accounting Team,

We are sending a GEODE contributor contract for signature to ${authorInfo.name} for the ${authorInfo.state} State Geothermal Data Report.

**Contributor Details:**
- Name: ${authorInfo.name}
- Email: ${authorInfo.email}
- Report: ${authorInfo.state} GEODE Report
- Chapter: ${authorInfo.chapter} - ${authorInfo.chapterTitle}
${paymentAmount ? `- Contract Value: ${paymentAmount}` : ''}
${paymentSchedule ? `- Payment Schedule: ${paymentSchedule}` : ''}

Please set up ${authorInfo.name} as a new contractor in our payment processing system.

The contract is attached for your records.

Thank you,
GEODE Team

---
This email was generated by Wellspring.`,
  };
}

/**
 * Email sent to author when a payment milestone is triggered
 * Includes a prefilled invoice attachment for the author to review and forward
 */
export function generateInvoiceReminderEmail(payment: PaymentTriggerInfo & {
  invoiceAttachment?: { filename: string; mimeType: string; base64: string };
}): {
  to: string[];
  cc: string[];
  subject: string;
  body: string;
  attachment?: { filename: string; mimeType: string; content: string };
} {
  const { authorInfo, milestoneLabel, paymentNumber, paymentAmount, invoiceAttachment } = payment;

  const hasInvoice = !!invoiceAttachment;

  const body = hasInvoice
    ? `Hi ${authorInfo.name.split(' ')[0]},

Great news! You've reached the "${milestoneLabel}" milestone for your ${authorInfo.state} GEODE Report chapter, which triggers Payment ${paymentNumber}${paymentAmount ? ` (${paymentAmount})` : ''}.

I've attached a prefilled invoice for your convenience. Please review it for accuracy, then:

1. Add your contact phone number (placeholder is marked)
2. Verify all details are correct
3. Write "INVOICE" in the subject line and forward it to GEODE@projectinnerspace.org for payment processing

If you have any questions about the invoice or payment process, contact accounting@projectinnerspace.org.

Thank you for your contribution to the ${authorInfo.state} State Geothermal Data Report!

Best regards,
GEODE Team

---
This email was generated by Wellspring.`
    : `Hi ${authorInfo.name.split(' ')[0]},

Great news! You've reached the "${milestoneLabel}" milestone for your ${authorInfo.state} GEODE Report chapter, which triggers Payment ${paymentNumber}${paymentAmount ? ` (${paymentAmount})` : ''}.

To receive payment, please submit your invoice to GEODE@projectinnerspace.org with "INVOICE" in the subject line.

Please use the GEODE Invoice Template provided in your onboarding materials. Categorize fees by Facet-Task "3-6" in the invoice table.

If you need a copy of the invoice template, please let us know.

Thank you for your contribution to the ${authorInfo.state} State Geothermal Data Report!

Best regards,
GEODE Team

---
This email was generated by Wellspring.`;

  return {
    to: [authorInfo.email],
    cc: [], // Author may or may not CC Trent
    subject: `[GEODE] Payment ${paymentNumber} Ready - Please Review & Submit Invoice (${authorInfo.state} Report)`,
    body,
    ...(invoiceAttachment && {
      attachment: {
        filename: invoiceAttachment.filename,
        mimeType: invoiceAttachment.mimeType,
        content: invoiceAttachment.base64,
      },
    }),
  };
}

/**
 * Email sent when contract is fully signed (both parties)
 */
export function generateContractSignedNotificationEmail(contract: ContractInfo): {
  to: string[];
  cc: string[];
  subject: string;
  body: string;
} {
  const { authorInfo } = contract;

  return {
    to: [authorInfo.email],
    cc: [GEODE_EMAIL_RECIPIENTS.geode],
    subject: `[GEODE] Contract Signed - Welcome to the ${authorInfo.state} Report Team!`,
    body: `Hi ${authorInfo.name.split(' ')[0]},

Your GEODE contributor contract has been fully executed! Both you and Project InnerSpace have signed the agreement.

**Next Steps:**
1. You should have received a copy of the fully signed contract
2. Our accounting team has been notified to set you up in our payment system
3. You'll receive your first payment (Distribution 1) once the author onboarding step is complete

**Your Assignment:**
- Report: ${authorInfo.state} State Geothermal Data Report
- Chapter: ${authorInfo.chapter} - ${authorInfo.chapterTitle}

We're excited to have you on the team! If you have any questions, please reach out to the GEODE team.

Best regards,
GEODE Team

---
This email was generated by Wellspring.`,
  };
}

// ============================================
// PAYMENT MILESTONE DEFINITIONS
// ============================================

export interface PaymentMilestoneDefinition {
  workflowStep: string;
  milestoneLabel: string;
  paymentNumber: number;
  triggersInvoice: boolean;
  triggersAccountingSetup: boolean;
}

export const PAYMENT_MILESTONES: PaymentMilestoneDefinition[] = [
  {
    workflowStep: 'send_contract',
    milestoneLabel: 'Contract Sent for Signature',
    paymentNumber: 0,
    triggersInvoice: false,
    triggersAccountingSetup: true, // Email accounting to setup contractor
  },
  {
    workflowStep: 'awaiting_contract_signature',
    milestoneLabel: 'Contract Signed & Author Onboarded',
    paymentNumber: 1,
    triggersInvoice: true, // Payment 1 (37.5%) — triggers when contract signature step completes
    triggersAccountingSetup: false,
  },
  {
    workflowStep: 'author_approval_round_1',
    milestoneLabel: 'Author Review of First Draft Complete',
    paymentNumber: 2,
    triggersInvoice: true, // Payment 2 (37.5%) — triggers when author's first review completes
    triggersAccountingSetup: false,
  },
  {
    workflowStep: 'author_approval_round_3',
    milestoneLabel: 'Final Publication Approval',
    paymentNumber: 3,
    triggersInvoice: true, // Payment 3 (25%) — triggers when author gives final approval
    triggersAccountingSetup: false,
  },
];

/**
 * Get the payment milestone definition for a workflow step
 */
export function getPaymentMilestone(workflowStep: string): PaymentMilestoneDefinition | null {
  return PAYMENT_MILESTONES.find(m => m.workflowStep === workflowStep) || null;
}

/**
 * Check if a workflow step triggers any payment-related email
 */
export function shouldSendPaymentEmail(workflowStep: string): {
  sendInvoiceReminder: boolean;
  sendAccountingSetup: boolean;
  milestone: PaymentMilestoneDefinition | null;
} {
  const milestone = getPaymentMilestone(workflowStep);

  return {
    sendInvoiceReminder: milestone?.triggersInvoice ?? false,
    sendAccountingSetup: milestone?.triggersAccountingSetup ?? false,
    milestone,
  };
}

// ============================================
// CONTRACT SIGNATURE MONITORING
// ============================================

export interface ContractSignatureStatus {
  authorSigned: boolean;
  authorSignedDate?: string;
  innerspaceSigned: boolean;
  innerspaceSignedDate?: string;
  fullyExecuted: boolean;
}

/**
 * Email subjects/patterns to monitor for contract signatures
 */
export const CONTRACT_SIGNATURE_PATTERNS = {
  // Box Sign patterns
  boxSignCompleted: /document.*signed|signature.*complete|fully.*executed/i,
  boxSignAuthorSigned: /has signed|signature received/i,

  // DocuSign patterns
  docuSignCompleted: /completed|all parties have signed/i,
  docuSignAuthorSigned: /has signed|signature received/i,

  // General patterns
  contractKeywords: /geode|contributor.*contract|author.*agreement/i,
};

/**
 * Parse an email to check for contract signature updates
 * This would be called by an email monitoring service
 */
export function parseContractSignatureEmail(
  subject: string,
  body: string,
  from: string
): {
  isContractRelated: boolean;
  signatureType: 'author' | 'innerspace' | 'fully_executed' | null;
  authorName?: string;
  state?: string;
} {
  const isContractRelated = CONTRACT_SIGNATURE_PATTERNS.contractKeywords.test(subject) ||
                            CONTRACT_SIGNATURE_PATTERNS.contractKeywords.test(body);

  if (!isContractRelated) {
    return { isContractRelated: false, signatureType: null };
  }

  // Check for fully executed
  if (CONTRACT_SIGNATURE_PATTERNS.boxSignCompleted.test(subject) ||
      CONTRACT_SIGNATURE_PATTERNS.docuSignCompleted.test(subject)) {
    return { isContractRelated: true, signatureType: 'fully_executed' };
  }

  // Check for author signature
  if (CONTRACT_SIGNATURE_PATTERNS.boxSignAuthorSigned.test(body) ||
      CONTRACT_SIGNATURE_PATTERNS.docuSignAuthorSigned.test(body)) {
    // Determine if it's the author or InnerSpace signing
    const isDani = from.toLowerCase().includes('dani') ||
                   body.toLowerCase().includes('dani toler') ||
                   body.toLowerCase().includes('project innerspace');

    return {
      isContractRelated: true,
      signatureType: isDani ? 'innerspace' : 'author',
    };
  }

  return { isContractRelated: true, signatureType: null };
}

// ============================================
// INVOICE TEMPLATE INFO
// ============================================

export const INVOICE_TEMPLATE = {
  path: '/Users/trentmcfadyen/Documents/Project InnerSpace/GEODE/GEODE Invoice Template.docx',
  googleDriveUrl: null as string | null, // Can be set if uploaded to Drive
};

/**
 * Get information about the invoice template for sharing with authors
 */
export function getInvoiceTemplateInfo(): {
  localPath: string;
  driveUrl: string | null;
  instructions: string;
} {
  return {
    localPath: INVOICE_TEMPLATE.path,
    driveUrl: INVOICE_TEMPLATE.googleDriveUrl,
    instructions: `
Invoice Submission Instructions:
1. Download the GEODE Invoice Template
2. Fill in your information and payment details
3. Submit to: invoice@projectinnerspace.org, accounting@projectinnerspace.org, geode@projectinnerspace.org
4. Include your chapter number and state report name in the invoice
    `.trim(),
  };
}
